name: Test SentinelScan

on: [push, pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest
    name: Running Sentinel Scanner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SentinelScan
        id: scan
        uses: ./backend
        with:
          target-dir: '.' 
          # MUDANÃ‡A AQUI: Usamos o caminho absoluto do workspace
          output-file: ${{ github.workspace }}/security_report.json
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      - name: Show Report
        if: always() 
        # O ficheiro agora vai aparecer na raiz, onde o cat espera
        run: cat security_report.json

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security_report.json